name: Build and Deploy on Self-Hosted

on:
  push:
    branches:
      - radix

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Pull latest code
      run: |
        git pull origin main

    - name: Clean output directory
      run: |
        rm -rf /opt/komari/data/data/theme/FrostPeakPulse/*
    
    - name: Build project
      run: |
        npm install
        npm run build

    - name: Copy build output and assets
      run: |
        cp -r ./dist /opt/komari/data/data/theme/FrostPeakPulse/
        cp ./komari-theme.json ./preview.png /opt/komari/data/data/theme/FrostPeakPulse/
